 
---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: fec6-sriov-vfio-smci00-server-profile-du-supermicro00
  namespace: openshift-sriov-network-operator
spec:
  resourceName: "vran_vfio_fh"
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/fec6-sriov-vfio_fh-server-profile-du-supermicro00: ""
  deviceType: vfio-pci
  priority: 10
  #mtu: 1500
  numVfs: 32
  nicSelector:
    vendor: "8086"
    deviceID: "158b"
    pfNames:
          - ens1f0#0-7
    
---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: fec6-sriov-vfio-ar-smci00-server-profile-du-supermicro00
  namespace: openshift-sriov-network-operator
spec:
  resourceName: "vran_vfio_ar"
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/fec6-sriov-vfio_ar-server-profile-du-supermicro00: ""
  deviceType: vfio-pci
  priority: 10
  #mtu: 1500
  numVfs: 32
  nicSelector:
    vendor: "8086"
    deviceID: "158b"
    pfNames:
          - ens1f1#0-7
    
---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: fec6-sriov-netdevice-smci00-server-profile-du-supermicro00
  namespace: openshift-sriov-network-operator
spec:
  resourceName: "vran_netdevice_mgmt_mh"
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/fec6-sriov-netdevice_mgmt_mh-server-profile-du-supermicro00: ""
  deviceType: netdevice
  priority: 10
  #mtu: 1500
  numVfs: 32
  nicSelector:
    vendor: "8086"
    deviceID: "158b"
    pfNames:
          - ens1f1#8-15
    
---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: fec6-sriov-netdevice-fh-smci00-server-profile-du-supermicro00
  namespace: openshift-sriov-network-operator
spec:
  resourceName: "vran_netdevice_mp"
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/fec6-sriov-netdevice_mp-server-profile-du-supermicro00: ""
  deviceType: netdevice
  priority: 10
  #mtu: 1500
  numVfs: 32
  nicSelector:
    vendor: "8086"
    deviceID: "158b"
    pfNames:
          - ens1f0#8-15
    
