apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - 00_namespace.yaml
  - 01_operatorgroup.yaml
  - 02_subscription.yaml
  - 03_hub.yaml
  - 04_add_subscription_permission.yaml

secretGenerator:
  - name: acm-secret
    namespace: open-cluster-management
    files:
    - .dockerconfigjson=secret.json
    type: kubernetes.io/dockerconfigjson
