---
apiVersion: sriovfec.intel.com/v1
kind: SriovFecClusterConfig
metadata:
  name: config
  namespace: vran-acceleration-operators
spec:
  nodes:
    - nodeName: worker-2-du
      physicalFunctions:
        - pciAddress: 0000:6a:00.0
          pfDriver: pci-pf-stub
          vfDriver: vfio-pci
          vfAmount: 8
          bbDevConfig:
            n3000:
              networkType: "FPGA_LTE"
              pfMode: False
              flrTimeout: 610
              downlink:
                bandwidth: 3
                loadBalance: 128
                queues:
                  vf0: 16
                  vf1: 16
                  vf2: 16
                  vf3: 16
                  vf4: 16
                  vf5: 16
                  vf6: 16
                  vf7: 16
              uplink:
                bandwidth: 12
                loadBalance: 128
                queues:
                  vf0: 16
                  vf1: 16
                  vf2: 16
                  vf3: 16
                  vf4: 16
                  vf5: 16
                  vf6: 16
                  vf7: 16
    