apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-node-autolabeler
  namespace: common-ran-subscriptions
placementRef:
  name: placement-policy-node-autolabeler
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-node-autolabeler
  kind: Policy
  apiGroup: policy.open-cluster-management.io
