apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-node-autolabeler
  namespace: common-ran-subscriptions
spec:
  clusterSelector:
    matchExpressions:
      - {key: profile, operator: In, values: [cu, du, cu-du, du-sno]}
