apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: hw-type-ran-subscription
  namespace: hw-type-ran-subscriptions
  labels:
    app: hw-type-ran-subscription
  annotations:
    apps.open-cluster-management.io/git-path: manifests/hw-type
    apps.open-cluster-management.io/git-branch: main
spec:
  channel: hw-type-ran-subscriptions/hw-type-ran-subscription 
  placement:
    local: true
