apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: hw-type-ran-subscription
  namespace: hw-type-ran-subscriptions
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - hw-type-ran-subscription
