# These manifests apply to every RAN cluster
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  cluster: base-ran-cu

bases:
  # Additional Operators for CU sites
  # OpenShiftVirt
  - ../operators/openshift-virtualization
  