---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
    openshift.io/run-level: "1"
  name: openshift-performance-addon-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-performance-addon-operator
  namespace: openshift-performance-addon-operator
spec:
  targetNamespaces:
  - openshift-performance-addon-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: performance-addon-operator-subscription
  namespace: openshift-performance-addon-operator
spec:
  channel: "4.6"
  installPlanApproval: Automatic
  name: performance-addon-operator
  # Modify source name of the catalogsource for air-gapped deployments
  source: "vran-automation-operator-catalog"
  sourceNamespace: openshift-marketplace
