---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-cu-ldc6-server-profile-cu-dell-r740-00

commonAnnotations:
 #argocd.argoproj.io/sync-wave: "20"
 argocd.argoproj.io/sync-options: Prune=false
 argocd.argoproj.io/compare-options: IgnoreExtraneous
# Apps of Apps
resources:
  - 40-controlplane-cluster-1-ldc6-dell-cu.yaml
  - 50-controlplane-cluster-1-ldc6-dell-cu-00-pre.yaml
  - 60-controlplane-cluster-1-ldc6-dell-cu-01-post.yaml
  - 70-controlplane-cluster-1-ldc6-dell-cu-02-virt.yaml
  - 80-controlplane-cluster-1-ldc6-dell-cu-02-settings.yaml
