---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./fec6/supermicro/du
  - ./ldc6/dell/cu

# Apps of Apps
resources:

  # - 10-gemini.yaml
  - 10-controlplane-cluster-1.yaml
  - 20-controlplane-cluster-1-sriovconfig.yaml
  - 30-controlplane-cluster-1-ptpconfig.yaml