---
apiVersion: v1
kind: Service
metadata:
  name: ds-service
  namespace: default
spec:
  clusterIP: None
  selector:
    app: timing-manager-pod
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
