---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-du-fec6-server-profile-du-supermicro00

resources:
  # SRIOV Configs
  - 00-Service.yaml
  - 01-Timing-Deployment-fec6.yaml
