---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    # argocd.argoproj.io/sync-wave: "30"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: n3000op-wait-fec6-server-profile-du-supermicro00
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - image: vran-prov-server.prov.ibmlab.lan:5000/ocp4/openshift4:4.6.16-cli
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/mcp
              echo ""
              echo -n "Waiting for the n3000 operator to be installed."
              sleep $SLEEP
              oc rollout status daemonset -n vran-acceleration-operators n3000-daemonset --timeout 300s
              echo "DONE"
          imagePullPolicy: Always
          name: n3000op-wait-job
          env:
          - name: SLEEP
            value: "5"
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30
