---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: Prune=false
  argocd.argoproj.io/compare-options: IgnoreExtraneous 
resources:
  - 00-n3000operator-wait-job.yaml
  - 01-n3000snp-wait-fecop-job.yaml
  - 02-install-sriov-fec.yaml
