---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    # argocd.argoproj.io/sync-wave: "30"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: scc-job-du-fec6-server-profile-du-supermicro00
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - image: vran-prov-server.prov.ibmlab.lan:5000/ocp4/openshift4:4.6.16-cli
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/mcp
              echo ""
              echo -n "Apply permissions for service account"
              oc adm policy  add-scc-to-user privileged system:serviceaccount:$NAMESPACE:$SA
              echo "DONE"
          imagePullPolicy: Always
          name: scc-apply-job
          env:
          - name: SA 
            value: dp-sa-r
          - name: NAMESPACE
            value: altiostar-4g-du-fec6 
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30