apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 50-master-chrony-conf
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,ZHJpZnRmaWxlIC92YXIvbGliL2Nocm9ueS9kcmlmdAptYWtlc3RlcCAxLjAgLTEKcnRjc3luYwpsb2dkaXIgL3Zhci9sb2cvY2hyb255CnNlcnZlciBudHAuaXhvLm5vIGlidXJzdApzZXJ2ZXIgbnMyLmN1c3RvbWVyLXJlc29sdmVyLm5ldCBpYnVyc3QK
          verification: {}
        filesystem: root
        mode: 420
        path: /etc/chrony.conf
