---
apiVersion: config.openshift.io/v1
kind: Image
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  name: cluster
spec:
  additionalTrustedCA:
    name: quay-leo-config
  registrySources:
    insecureRegistries:      
    - vran-prov-server.prov.ibmlab.lan:5000
