---
apiVersion: performance.openshift.io/v1
kind: PerformanceProfile
metadata:
  name: ran-cu-ldc6-server-profile-cu-dell-r740-00-pao-profile-cu-dell-r740-00
spec:
  cpu:
    isolated: "4-47,52-95"
    reserved: "0-3,48-51"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 176
      node: 0 
    - size: "1G"
      count: 176
      node: 1 
  numa:
    topologyPolicy: best-effort
  nodeSelector:
    node-role.kubernetes.io/ran-cu-ldc6-server-profile-cu-dell-r740-00: ""
