# These manifests apply to every RAN cluster
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  cluster: base-ran-du

bases:
  # Additional Operators for DU sites
  # PTP
  - ../operators/openshift-ptp
  # Intel N3000
  - ../operators/vran-acceleration-operator