---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: controlplane-cluster-1-fec6-du-du-03-deploy
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '80'
spec:
  # The project the application belongs to.
  project: default
  destination:
    name: ''
    #namespace: ''
    server: 'https://api.controlplane-cluster-1.prov.ibmlab.lan:6443'
  # Source of the application manifests
  source:
    repoURL: 'https://github.com/traghave123/ztp-ran-manifests.git'
    targetRevision: HEAD
    path: ran-manifests/manifests/controlplane-cluster-1/fec6/supermicro/du/du-03
    directory:
      recurse: false
  # Sync policy
  syncPolicy:
    automated: 
      prune: false
      selfHeal: true 
      allowEmpty: false
    syncOptions:
      # (equivalent to 'kubectl apply --validate=true')
      - Validate=false
      - CreateNamespace=true
    retry:
      # unlimited if less than 0
      limit: -1
      backoff:
        # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        duration: 5s
        # a factor to multiply the base duration after each failed retry
        factor: 2
        # the maximum amount of time allowed for the backoff strategy
        maxDuration: 3m