---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # annotations:
  #   argocd.argoproj.io/sync-wave: "1"
  name: cli-job-sa-role
rules:
  - apiGroups:
      - apiextensions.k8s.io
      - machineconfiguration.openshift.io
    resources:
      - customresourcedefinitions
      - machineconfigpools
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list 
      - patch
  - apiGroups:
      - sriovnetwork.openshift.io
    resources:
      - sriovnetworknodepolicies
    verbs:
      - get
      - list
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
    verbs:
      - get
      - list
      - update
      - create
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - get
      - list  
      - update    
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - privileged  
    verbs:
      - use
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - privileged
    verbs:
      - use
  - apiGroups:
      - fpga.intel.com
    resources:
      - n3000clusters
    verbs:
      - get
      - list
      - update