---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-cnv
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kubevirt-hyperconverged-group
  namespace: openshift-cnv
spec:
  targetNamespaces:
    - openshift-cnv
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: hco-operatorhub
  namespace: openshift-cnv
spec:
  config:
    ## Specify where the operator infrstructure should run
     nodeSelector:
       node-role.kubernetes.io/master: ""
     tolerations:
     - effect: NoSchedule
       key: node-role.kubernetes.io/master
       operator: Exists
  # Modify source name of the catalogsource for isolated network deployments
  source: "vran-automation-operator-catalog"
  sourceNamespace: openshift-marketplace
  name: kubevirt-hyperconverged
  channel: "stable"