---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
#    argocd.argoproj.io/sync-wave: "30"
  name: nodes-label-job-worker-2-du
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - image: vran-prov-server.prov.ibmlab.lan:5000/ocp4/openshift4:4.6.16-cli
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/node
              echo ""
              echo -n "Add node labels"
              until oc wait --selector=node-role.kubernetes.io/ran-du-fec6-server-profile-du-supermicro00='',kubernetes.io/hostname=worker-2-du --for=condition=ready nodes
              do
                echo -n "...still waiting for applying labels"
                oc label node worker-2-du node-role.kubernetes.io/ran-du-fec6-server-profile-du-supermicro00=""
                oc label node worker-2-du ran.openshift.io/fec6-sriov-vfio_fh-server-profile-du-supermicro00=""
                oc label node worker-2-du ran.openshift.io/fec6-sriov-vfio_ar-server-profile-du-supermicro00=""
                oc label node worker-2-du ran.openshift.io/fec6-sriov-netdevice_mgmt_mh-server-profile-du-supermicro00=""
                oc label node worker-2-du ran.openshift.io/fec6-sriov-netdevice_mp-server-profile-du-supermicro00=""
                oc label node worker-2-du ran.openshift.io/fec6-ptp-server-profile-du-supermicro00=""
                oc label node worker-2-du ran.openshift.io/n3k=""
                oc label node worker-2-du ran.openshift.io/ptp=""
                oc label node worker-2-du ran.openshift.io/sriov=""

                sleep $SLEEP
              done
              echo "DONE"
          imagePullPolicy: Always
          name: nodes-label-job
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30